[workspace]
resolver = "3"
members = [
    "crates/operow-core",
    "crates/operow-engine",
    "crates/operow-app",
    "crates/operow-dbc",
    "crates/operow-log",
]

[workspace.package]
edition = "2024"
version = "0.1.0"
license = "MIT"

[workspace.dependencies]
serde = { version = "1", features = ["derive"] }
thiserror = "2"
crossbeam-channel = "0.5"
operow-core = { path = "crates/operow-core" }
