[package]
name = "operow-engine"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
operow-core = { workspace = true }
operow-log = { path = "../operow-log" }
operow-hw = { path = "../operow-hw" }
crossbeam-channel = { workspace = true }
rhai = { version = "1.26.1", features = ["sync"] }
thiserror.workspace = true
operow-isotp = { path = "../operow-isotp" }
operow-uds = { path = "../operow-uds" }
