[package]
name = "operow-app"
edition.workspace = true
version.workspace = true
license.workspace = true

[[bin]]
name = "operow"
path = "src/main.rs"

[dependencies]
eframe = { version = "0.33", features = ["persistence"] }
egui = "0.33"
egui_extras = { version = "0.33", features = ["svg"] }
egui-flow = { git = "https://github.com/niketdhale/egui-flow", rev = "7c8d5a3c7bee0f2547eaca8cd5ca0014cb5cd220" }
rfd = "0.15"
serde_json = "1"
image = { version = "0.25", default-features = false, features = ["png"] }
operow-core = { workspace = true }
operow-engine = { path = "../operow-engine" }
operow-dbc = { path = "../operow-dbc" }
egui_dock = { version = "0.18", features = ["serde"] }
serde = { workspace = true, features = ["derive"] }
egui_plot = "0.34"
